Repository Tsuser1/Modern-LWC, pull requests merged in 2018-08, with the labels that each got.

#12 Update lwc_de.properties
  src/lang/lwc_de.properties
Labels: enhancement

#13 Update of the Polish translation by RikoDEV
  src/lang/lwc_pl.properties
Labels: enhancement

#10 Set useSSL property to false for MySQL connections
  src/main/java/com/griefcraft/sql/Database.java
Labels: enhancement, good first issue

#19 Fix getting a player in a range
  src/main/java/com/griefcraft/lwc/LWC.java
Labels: bug
